# WEEK 1 : DATA PRE-PROCESSING

Import Libraries

In [1]:

import os
import pandas as pd
import numpy as np

# Define File Paths
RAW_PATH = os.path.join("data", "raw", "Airline Dataset Updated - v2.csv")
SAMPLE_PATH = os.path.join("data", "processed", "sample_200k.csv")

# Set Display Options
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

Load Dataset

In [2]:

df = pd.read_csv(os.path.join("..", "data", "raw", "Airline Dataset Updated - v2.csv"), nrows=200_000)
df.shape

(98619, 15)

In [3]:
df.head(15)

,Passenger ID,First Name,Last Name,Gender,Age,Nationality,Airport Name,Airport Country Code,Country Name,Airport Continent,Continents,Departure Date,Arrival Airport,Pilot Name,Flight Status
0,ABVWIg,Edithe,Leggis,Female,62,Japan,Coldfoot Airport,US,United States,NAM,North America,6/28/2022,CXF,Fransisco Hazeldine,On Time
1,jkXXAX,Elwood,Catt,Male,62,Nicaragua,Kugluktuk Airport,CA,Canada,NAM,North America,12/26/2022,YCO,Marla Parsonage,On Time
2,CdUz2g,Darby,Felgate,Male,67,Russia,Grenoble-Isère Airport,FR,France,EU,Europe,1/18/2022,GNB,Rhonda Amber,On Time
3,BRS38V,Dominica,Pyle,Female,71,China,Ottawa / Gatineau Airport,CA,Canada,NAM,North America,9/16/2022,YND,Kacie Commucci,Delayed
4,9kvTLo,Bay,Pencost,Male,21,China,Gillespie Field,US,United States,NAM,North America,2/25/2022,SEE,Ebonee Tree,On Time
5,nMJKVh,Lora,Durbann,Female,55,Brazil,Coronel Horácio de Mattos Airport,BR,Brazil,SAM,South America,06-10-2022,LEC,Inglis Dolley,On Time
6,8IPFPE,Rand,Bram,Male,73,Ivory Coast,Duxford Aerodrome,GB,United Kingdom,EU,Europe,10/30/2022,QFO,Stanislas Tiffin,Cancelled
7,pqixbY,Perceval,Dallosso,Male,36,Vietnam,Maestro Wilson Fonseca Airport,BR,Brazil,SAM,South America,04-07-2022,STM,Sharyl Eastmead,Cancelled
8,QNAs2R,Aleda,Pigram,Female,35,Palestinian Territory,Venice Marco Polo Airport,IT,Italy,EU,Europe,8/20/2022,VCE,Daryn Bardsley,On Time
9,3jmudz,Burlie,Schustl,Male,13,Thailand,Vermilion Airport,CA,Canada,NAM,North America,04-06-2022,YVG,Alameda Carlyle,On Time
10,2P41gZ,Porty,Jori,Male,39,Tunisia,Nuevo Casas Grandes Airport,MX,Mexico,NAM,North America,5/27/2022,NCG,Rasia Fidelus,Cancelled
11,sBf524,Briant,De La Haye,Male,71,Russia,Ruben Cantu Airport,PA,Panama,NAM,North America,02-06-2022,SYP,Alina Flooks,Delayed
12,PlwJZT,Kalie,Scoble,Female,47,Sweden,Loralai Airport,PK,Pakistan,AS,Asia,3/19/2022,LRG,Madelena Lennarde,Delayed
13,iU75x3,Catriona,Beaument,Female,77,Russia,Cudal Airport,AU,Australia,OC,Oceania,3/24/2022,CUG,Margie Beal,Delayed
14,GUta6R,Amberly,Handling,Female,32,China,Farmington Regional Airport,US,United States,NAM,North America,03-07-2022,FAM,Lothaire Eades,Delayed

Create Schema Table (column names + data types)

In [4]:
schema = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str)
}).sort_values("dtype")

print("Total columns:", len(df.columns))
schema

Total columns: 15

                                    column   dtype
Age                                    Age   int64
Passenger ID                  Passenger ID  object
First Name                      First Name  object
Last Name                        Last Name  object
Gender                              Gender  object
Nationality                    Nationality  object
Airport Name                  Airport Name  object
Airport Country Code  Airport Country Code  object
Country Name                  Country Name  object
Airport Continent        Airport Continent  object
Continents                      Continents  object
Departure Date              Departure Date  object
Arrival Airport            Arrival Airport  object
Pilot Name                      Pilot Name  object
Flight Status                Flight Status  object

Checking Missing Values

In [5]:
missing_count = df.isna().sum().sort_values(ascending=False)
missing_pct = (missing_count / len(df) * 100).round(2)

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_pct": missing_pct
})

print("Top 20 columns with missing values:")
missing_summary.head(20)

Top 20 columns with missing values:

                      missing_count  missing_pct
Passenger ID                      0          0.0
First Name                        0          0.0
Last Name                         0          0.0
Gender                            0          0.0
Age                               0          0.0
Nationality                       0          0.0
Airport Name                      0          0.0
Airport Country Code              0          0.0
Country Name                      0          0.0
Airport Continent                 0          0.0
Continents                        0          0.0
Departure Date                    0          0.0
Arrival Airport                   0          0.0
Pilot Name                        0          0.0
Flight Status                     0          0.0

Checking Duplicate Values

In [6]:
dup_count = df.duplicated().sum()
print("Duplicate rows found:", dup_count)

Duplicate rows found: 0

Numeric Column Summary

In [7]:
desc_num = df.describe(include="number").T
print("Numeric summary (first 25 rows):")
desc_num.head(25)

Numeric summary (first 25 rows):

       count       mean        std  min   25%   50%   75%   max
Age  98619.0  45.504021  25.929849  1.0  23.0  46.0  68.0  90.0

Negative values check in numeric columns

In [8]:

num_cols = df.select_dtypes(include="number").columns.tolist()
print("Numeric columns found:", num_cols)


neg_counts = {}
for c in num_cols:
    s = pd.to_numeric(df[c], errors="coerce")
    neg_counts[c] = int((s < 0).sum())

neg_table = pd.DataFrame({"negative_values_count": neg_counts}).sort_values("negative_values_count", ascending=False)
print("Columns with negative values (top 15):")
neg_table.head(15)

Numeric columns found: ['Age']
Columns with negative values (top 15):

     negative_values_count
Age                      0

Numeric Range Summary

In [9]:

summary = df[num_cols].describe().T[["min", "max", "mean"]].sort_values("max", ascending=False)
print("Numeric range summary (top 20 by max):")
summary.head(20)

Numeric range summary (top 20 by max):

     min   max       mean
Age  1.0  90.0  45.504021

Top 10 columns that have the most missing

In [10]:
df.isna().sum().sort_values(ascending=False).head(10)

Passenger ID            0
First Name              0
Last Name               0
Gender                  0
Age                     0
Nationality             0
Airport Name            0
Airport Country Code    0
Country Name            0
Airport Continent       0
dtype: int64

Saving Processed Data file

In [11]:

processed_path = os.path.join("..", "data", "processed", "week1_sample.csv")

# Save file
df.to_csv(processed_path, index=False)

print("Week 1 processed sample saved at:")
print(processed_path)

Week 1 processed sample saved at:
..\data\processed\week1_sample.csv

### Week 1 Key Insights 

The initial phase of the AirFly Insights project focused on understanding,
cleaning, and preparing the raw aviation dataset for further analytical processing.

### Outcomes

- Improved dataset consistency and usability.
- Eliminated structural data quality issues.
- Prepared reliable input data for feature engineering in Week 2.

This stage ensured that subsequent analytical results are based on
clean, structured, and trustworthy data.